### ISSUE TITLE
patch.sh version detection not working properly

### ISSUE THREAD

**Issue by person4268** [im-0/hpsahba#18]
On my system, running 5.14.8, it detected my kernel as 5.8, instead of 5.14, so it downloaded the wrong driver.

uname -r output: `5.14.8-arch1-1`

**Comment by BASS10** [comment]
The version detection doesn't work because there is no version detection! The `VERSION=${1:-5.8}` line is saying "use the first command line argument and default to 5.8 if none is provided". So you need to run `./patch.sh 5.14` or whatever suits your situation. This caught me out too as it's not obvious from the instructions.

Alternatively you could edit patch.sh as follows and it _should_ automatically detect your kernel version, while still allowing manual override.
`VERSION=${1:-$(uname -r | grep -o "^[0-9]*[.][0-9]*")}`
